# AI Services 简化配置示例
# 这是一个最小化的配置文件，包含最常用的设置

version: "1.0"

# 基础服务配置
services:
  
  # 聊天服务 - 使用Ollama
  chat:
    default_provider: "ollama"
    providers:
      ollama:
        base_url: "http://localhost:11434"
        model_name: "qwen3:1.7b"  # 确保这个模型已安装
        timeout: 30.0
        options:
          temperature: 0.7  # 控制回答的创造性 (0.0-1.0)
  
  # 嵌入服务 - 使用Ollama
  embedding:
    default_provider: "ollama"
    providers:
      ollama:
        base_url: "http://localhost:11434"
        model_name: "nomic-embed-text:latest"  # 嵌入模型
        timeout: 30.0
  
  # 重排序服务 - 使用Ollama
  rerank:
    default_provider: "ollama"
    providers:
      ollama:
        base_url: "http://localhost:11434"
        model_name: "qwen3:1.7b"  # 重排序模型
        timeout: 30.0

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null  # 设置文件路径以保存日志到文件